Repository yavl/teeworlds-infclassR, pull requests merged in 2019-02, with the labels that each got.

#83 Added IsZombie(), IsHuman(), rewrote IsInfected() to IsZombie()
  src/game/server/entities/biologist-laser.cpp
  src/game/server/entities/biologist-mine.cpp
  src/game/server/entities/bouncing-bullet.cpp
  src/game/server/entities/character.cpp
  src/game/server/entities/character.h
  src/game/server/entities/engineer-wall.cpp
  src/game/server/entities/growingexplosion.cpp
  src/game/server/entities/hero-flag.cpp
  src/game/server/entities/looper-wall.cpp
  src/game/server/entities/merc-bomb.cpp
  src/game/server/entities/projectile.cpp
  src/game/server/entities/scientist-mine.cpp
  src/game/server/entities/slug-slime.cpp
  src/game/server/entities/white-hole.cpp
  src/game/server/gamecontext.cpp
  src/game/server/gamecontroller.cpp
  src/game/server/gamemodes/mod.cpp
  src/game/server/player.cpp
  src/game/server/player.h
Labels: enhancement

#87 Tarzan-mode
  src/game/gamecore.cpp
  src/game/server/entities/character.cpp
Labels: new feature

#79 Added turret feature
  src/engine/server.h
  src/engine/shared/config_variables.h
  src/game/server/entities/character.cpp
  src/game/server/entities/character.h
  src/game/server/entities/growingexplosion.cpp
  src/game/server/entities/growingexplosion.h
  src/game/server/entities/hero-flag.cpp
  src/game/server/entities/merc-bomb.cpp
  src/game/server/entities/plasma.cpp
  src/game/server/entities/plasma.h
  src/game/server/entities/scientist-mine.cpp
  src/game/server/entities/soldier-bomb.cpp
  src/game/server/entities/turret.cpp
  src/game/server/entities/turret.h
  src/game/server/gamecontext.cpp
  src/game/server/gamecontext.h
  src/game/server/gameworld.h
Labels: cucumber, new feature

#99 If there are 3 players, 2 should become zombies
  src/game/server/gamemodes/mod.cpp
Labels: balance

#108 created a way to measure the performance of the server
  src/engine/server/measure_ticks.cpp
  src/engine/server/measure_ticks.h
  src/engine/server/server.cpp
  src/game/server/gamecontext.cpp
  src/game/server/gamecontext.h
Labels: incl. in dev, ready to merge

#105 Log players online + bug fixes (infclass-stats)
  src/game/server/entities/character.cpp
  src/game/server/gamemodes/mod.cpp
  src/game/server/gamemodes/mod.h
  src/game/server/player.cpp
Labels: enhancement
