Repository yavl/teeworlds-infclassR, pull requests merged in 2019-03, with the labels that each got.

#134 initial infection rewrite
  src/game/server/gamemodes/mod.cpp
Labels: ready to merge

#140 initial infection rewrite
  src/game/server/gamemodes/mod.cpp
Labels: enhancement

#144 Make scoring only possible with a higher amount of players on server
  src/engine/server/server.cpp
Labels: enhancement, ready to merge

#138 CountActivePlayers,CountHumans,CountZombies + Getter
  src/engine/server.h
  src/engine/server/server.cpp
  src/engine/server/server.h
  src/game/server/entities/hero-flag.cpp
  src/game/server/gamecontext.cpp
  src/game/server/gamecontext.h
  src/game/server/gamecontroller.cpp
  src/game/server/gamemodes/mod.cpp
  src/game/server/gamemodes/mod.h
  src/game/server/player.cpp
  src/game/server/player.h
Labels: bug, code optimazion, enhancement, incl. in dev
